name: Check Compilation

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check_compilation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v3
        with:
          install-binaryen: 'false'

      - name: Build Pico
        run: tinygo build -o pico-sketchy.uf2 -target=pico

      - name: Build Pico2
        run: tinygo build -o pico2-sketchy.uf2 -target=pico2

      - name: Compilation Successful
        run: echo "Compilation succeeded!"
