name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Responds to tag versions like v1.0.0

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Install TinyGo
      #  run: |
      #    wget https://github.com/tinygo-org/tinygo/releases/download/v0.41.1/tinygo0.41.1.linux-amd64.tar.gz
      #    tar -xzf tinygo0.41.1.linux-amd64.tar.gz
      #    sudo mv tinygo /usr/local/bin/

      - name: Setup Tinygo
        uses: acifani/setup-tinygo@v3
        with:
          install-binaryen: 'false'

      - name: Build Pico
        run: tinygo build -o pico-sketchy.uf2 -target=pico

      - name: Build Pico2
        run: tinygo build -o pico2-sketchy.uf2 -target=pico2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Your release notes here.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
