name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Responds to tag versions like v1.0.0

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Tinygo
        uses: acifani/setup-tinygo@v3
        with:
          install-binaryen: 'false'

      - name: Build Pico
        run: tinygo build -o pico-sketchy.uf2 -target=pico

      - name: Build Pico2
        run: tinygo build -o pico2-sketchy.uf2 -target=pico2

      - name: Create checksums
        run: sha256sum *.uf2 > SHA256SUMS.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          generate_release_notes: true
          files: |
            pico-sketchy.uf2
            pico2-sketchy.uf2
            SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
